name: train
services:
  jupyter:
    image: quay.io/jupyter/scipy-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - /home/cc/MLOPs-Project/train/workspace:/home/jovyan/work # mount workspace
    #command: >
    #  bash -c "python3 -m pip install numpy mlflow && start-notebook.sh"
